# Generated by Django 3.2.6 on 2021-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0004_auto_20211001_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'CEA'), ('2', 'MEC'), ('3', 'ELE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='phase',
            field=models.CharField(blank=True, choices=[('1', 'APD'), ('2', 'PEO'), ('3', 'DOE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='trade',
            field=models.CharField(blank=True, choices=[('1', 'CEA'), ('2', 'MEC'), ('3', 'ELE')], max_length=10, null=True),
        ),
    ]
