# Generated by Django 3.2.6 on 2021-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0010_auto_20211002_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annexe5',
            old_name='price',
            new_name='fabrication_total_price',
        ),
        migrations.AddField(
            model_name='annexe5',
            name='fabrication_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annexe5',
            name='material_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annexe5',
            name='material_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annexe5',
            name='transport_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annexe5',
            name='transport_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='annexe5',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
