# Generated by Django 3.2.6 on 2021-10-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0014_factureitem_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureitem',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.facture'),
        ),
    ]
