# Generated by Django 3.2.6 on 2021-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0017_auto_20211002_1710'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'no'), name='order-item-no'),
        ),
    ]
