# Generated by Django 3.2.6 on 2021-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0018_orderitem_order-item-no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
