# Generated by Django 3.2.6 on 2021-10-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0022_auto_20211002_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='no',
            new_name='number',
        ),
    ]
