# Generated by Django 3.2.6 on 2021-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0023_rename_no_order_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annexe5',
            name='project-annexe-no',
        ),
        migrations.RemoveConstraint(
            model_name='productcard',
            name='project-fp-no',
        ),
        migrations.RemoveConstraint(
            model_name='routageitems',
            name='routage-facture-no',
        ),
        migrations.RenameField(
            model_name='annexe5',
            old_name='no',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='coo',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='declaration',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='routage',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='tds',
            old_name='no',
            new_name='number',
        ),
        migrations.AddConstraint(
            model_name='annexe5',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='project-annexe-code'),
        ),
        migrations.AddConstraint(
            model_name='productcard',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='project-fp-number'),
        ),
        migrations.AddConstraint(
            model_name='routageitems',
            constraint=models.UniqueConstraint(fields=('routage', 'facture'), name='routage-facture-number'),
        ),
    ]
