# Generated by Django 3.2.6 on 2021-10-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0024_auto_20211002_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factureitem',
            old_name='item',
            new_name='order_item',
        ),
    ]
