# Generated by Django 3.2.6 on 2021-10-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0025_rename_item_factureitem_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='productcard',
            name='fp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.fptype'),
        ),
    ]
