# Generated by Django 3.2.6 on 2021-10-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0032_auto_20211013_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['no']},
        ),
        migrations.AlterField(
            model_name='declarationitem',
            name='facture_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarationfactures', to='fiche_produit.factureitem', unique=True),
        ),
        migrations.AlterField(
            model_name='specificationitem',
            name='facture_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specificationfactures', to='fiche_produit.factureitem', unique=True),
        ),
        migrations.AlterField(
            model_name='tdsitem',
            name='facture_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdsfactures', to='fiche_produit.factureitem', unique=True),
        ),
    ]
