# Generated by Django 3.2.6 on 2021-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0036_productcardannexe5_productcardroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='annexe5',
        ),
        migrations.AddField(
            model_name='productcard',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
