# Generated by Django 3.2.6 on 2021-11-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0041_auto_20211101_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technical_detail',
        ),
        migrations.CreateModel(
            name='TechnicalDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_image', models.ImageField(blank=True, null=True, upload_to='technical_image/')),
                ('productcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiche_produit.productcard')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDetailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_file', models.FileField(blank=True, null=True, upload_to='technical_file/')),
                ('productcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiche_produit.productcard')),
            ],
        ),
    ]
