# Generated by Django 3.2.6 on 2021-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='room_plan/'),
        ),
    ]
