# Generated by Django 3.2.6 on 2021-10-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0009_auto_20211002_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name_en', models.CharField(blank=True, max_length=3, null=True)),
                ('short_name_fr', models.CharField(blank=True, max_length=3, null=True)),
                ('short_name_ru', models.CharField(blank=True, max_length=3, null=True)),
                ('short_name_tm', models.CharField(blank=True, max_length=3, null=True)),
                ('name_en', models.CharField(blank=True, max_length=10, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=10, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('name_tm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=10, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=10, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('name_tm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='annexe5',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.currency'),
        ),
        migrations.AlterField(
            model_name='annexe5',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.unit'),
        ),
    ]
