# Generated by Django 3.2.6 on 2021-10-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0012_auto_20211002_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=10, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=10, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('name_tm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='factureitem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.currency'),
        ),
        migrations.AlterField(
            model_name='factureitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.unit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.currency'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.unit'),
        ),
        migrations.AlterField(
            model_name='factureitem',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiche_produit.packagetype'),
        ),
    ]
