# Generated by Django 3.2.6 on 2021-10-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0013_auto_20211002_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureitem',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
