# Generated by Django 3.2.6 on 2021-10-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0019_alter_orderitem_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='order',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='routage',
        ),
    ]
