# Generated by Django 3.2.6 on 2021-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0021_auto_20211002_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationitem',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tdsitem',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='declarationitem',
            constraint=models.UniqueConstraint(fields=('declaration', 'no'), name='declaration-item-no'),
        ),
        migrations.AddConstraint(
            model_name='routageitems',
            constraint=models.UniqueConstraint(fields=('routage', 'facture'), name='routage-facture-no'),
        ),
        migrations.AddConstraint(
            model_name='specificationitem',
            constraint=models.UniqueConstraint(fields=('specification', 'no'), name='specification-item-no'),
        ),
        migrations.AddConstraint(
            model_name='tdsitem',
            constraint=models.UniqueConstraint(fields=('tds', 'no'), name='tds-item-no'),
        ),
    ]
