# Generated by Django 3.2.6 on 2021-10-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0029_auto_20211008_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderorderitems', to='fiche_produit.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productcardorderitems', to='fiche_produit.productcard'),
        ),
    ]
