# Generated by Django 3.2.6 on 2021-10-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0030_auto_20211011_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutageItems',
            new_name='RoutageItem',
        ),
        migrations.AlterField(
            model_name='coofacture',
            name='coo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cootofacture', to='fiche_produit.coo'),
        ),
        migrations.AlterField(
            model_name='coofacture',
            name='facture_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturetocoo', to='fiche_produit.factureitem', unique=True),
        ),
        migrations.AlterField(
            model_name='declarationitem',
            name='declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarationitems', to='fiche_produit.declaration'),
        ),
        migrations.AlterField(
            model_name='factureitem',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factureitems', to='fiche_produit.facture'),
        ),
        migrations.AlterField(
            model_name='specificationitem',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='fiche_produit.specification'),
        ),
        migrations.AlterField(
            model_name='tdsitem',
            name='tds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdsitems', to='fiche_produit.tds'),
        ),
    ]
