# Generated by Django 3.2.6 on 2021-10-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0031_auto_20211013_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='technical_detail',
            field=models.FileField(blank=True, null=True, upload_to='technical_detail/'),
        ),
        migrations.AlterField(
            model_name='routageitem',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturetoroutageitem', to='fiche_produit.facture'),
        ),
        migrations.AlterField(
            model_name='routageitem',
            name='routage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routagetoroutageitem', to='fiche_produit.routage'),
        ),
    ]
