# Generated by Django 3.2.6 on 2021-10-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0033_auto_20211018_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitemsinfactureitems', to='fiche_produit.orderitem'),
        ),
    ]
