# Generated by Django 3.2.6 on 2021-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0034_alter_factureitem_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fptype',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
