# Generated by Django 3.2.6 on 2021-10-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_produit', '0038_auto_20211029_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='annexe5s',
            field=models.ManyToManyField(blank=True, null=True, through='fiche_produit.ProductCardAnnexe5', to='fiche_produit.Annexe5'),
        ),
        migrations.RemoveField(
            model_name='productcardannexe5',
            name='annexe5',
        ),
        migrations.AddField(
            model_name='productcardannexe5',
            name='annexe5',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fiche_produit.annexe5'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productcardannexe5',
            name='productcard',
        ),
        migrations.AddField(
            model_name='productcardannexe5',
            name='productcard',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fiche_produit.productcard'),
            preserve_default=False,
        ),
    ]
